import { NativeModules } from 'react-native';
import type { ConfigValue } from './src/NativeUltimateConfig';

export type { ConfigValue, Spec } from './src/NativeUltimateConfig';

type Config = Record<string, ConfigValue>;

// override.js is dynamically generated by the rncu CLI.
// It contains platform-specific overrides. Do not commit override.js to git.
// eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires
const override: Config = require('./override');

const { UltimateConfig } = NativeModules;

export default {
  ...(UltimateConfig as Config | undefined),
  ...override,
} as Config;
